from .user import *
from .courses import *
from .program import *
from .staff import *
from .student import *
from .programCourses import *
from .prerequisites import *
from .coursePlan import *
from .department import *
