from .user import *
from .course import *
from .program import *
from .staff import *
from .student import *
from .prerequisites import *
from .coursePlan import *
from .department import *
from .semester import *
from .studentCourse import *
from .courseProgram import *
from .courseHistory import *